import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "@/providers/Providers";

export const metadata: Metadata = {
  title: "Next Mart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" data-theme="light">
        <body>
          <Toaster richColors position="top-center" />
          <div>{children}</div>
        </body>
      </html>
    </Providers>
  );
}
